sections:
  - name: "Stereo Vision"
    instructions: | 
      This label represents arXiv articles that discuss the release of articles related to stereo vision.
    label: "stereo-vision"
    threshold: 0.7
  - name: "Geospatial Foundation Models"
    instructions: |
      This label represents arXiv articles about geospatial foundation models.
    label: "geo-fm"
    threshold: 0.6
  - name: "Synthetic satellite data"
    instructions: |
      This label represents arXiv articles about Synthetic satellite data.
    label: "synth-sat"
    threshold: 0.6
  - name: "Graph Neural Network"
    instructions: |
      This label represents arXiv articles about GNNs.
    label: "gnn"
    threshold: 0.6
